import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
GD32E23x_standard_peripheral/Source/gd32e23x_gpio.c
GD32E23x_standard_peripheral/Source/gd32e23x_rcu.c
GD32E23x_standard_peripheral/Source/gd32e23x_exti.c
GD32E23x_standard_peripheral/Source/gd32e23x_misc.c
GD32E23x_standard_peripheral/Source/gd32e23x_syscfg.c
''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_spi.c']

if GetDepend(['RT_USING_CAN']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_can.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_enet.c']

if GetDepend(['RT_USING_ADC']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_dac.c']

if GetDepend(['RT_USING_RTC']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_rtc.c']
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_pmu.c']

if GetDepend(['RT_USING_WDT']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_wwdgt.c']
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_fwdgt.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_sdio.c']
    src += ['GD32E23x_standard_peripheral/Source/gd32e23x_dma.c']

path = [cwd + '/GD32E23x_standard_peripheral/Include']

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = ['SOC_SERIES_GD32E23x'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
